"""Se agrego relaciones a las promociones

Revision ID: 6e795633b872
Revises: ecb4aaa788ae
Create Date: 2025-07-13 20:14:14.314068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e795633b872'
down_revision: Union[str, Sequence[str], None] = 'ecb4aaa788ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
