"""Se agrego relaciones a las promociones2

Revision ID: 6fa3c2cb2005
Revises: 6e795633b872
Create Date: 2025-07-13 20:18:17.765011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa3c2cb2005'
down_revision: Union[str, Sequence[str], None] = '6e795633b872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
