"""Se agrego modelos de cupones y complementaciones de los carritos

Revision ID: a8f24885de19
Revises: 
Create Date: 2025-07-09 00:20:40.597086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f24885de19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cupon_usos', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('cupon_usos', sa.Column('cupon_id', sa.Integer(), nullable=True))
    op.add_column('cupon_usos', sa.Column('fecha_uso', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'cupon_usos', 'cupones', ['cupon_id'], ['id'])
    op.create_foreign_key(None, 'cupon_usos', 'users', ['usuario_id'], ['id'])
    op.add_column('cupones', sa.Column('codigo', sa.String(), nullable=True))
    op.add_column('cupones', sa.Column('descuento', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('cupones', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('cupones', sa.Column('fecha_expiracion', sa.DateTime(), nullable=False))
    op.add_column('cupones', sa.Column('max_usos_por_usuario', sa.Integer(), nullable=True))
    op.add_column('cupones', sa.Column('max_usos_global', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cupones_codigo'), 'cupones', ['codigo'], unique=True)
    op.add_column('pedido_items', sa.Column('pedido_id', sa.Integer(), nullable=True))
    op.add_column('pedido_items', sa.Column('producto_id', sa.Integer(), nullable=True))
    op.add_column('pedido_items', sa.Column('cantidad', sa.Integer(), nullable=True))
    op.add_column('pedido_items', sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'pedido_items', 'pedidos', ['pedido_id'], ['id'])
    op.create_foreign_key(None, 'pedido_items', 'productos', ['producto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedido_items', type_='foreignkey')
    op.drop_constraint(None, 'pedido_items', type_='foreignkey')
    op.drop_column('pedido_items', 'precio_unitario')
    op.drop_column('pedido_items', 'cantidad')
    op.drop_column('pedido_items', 'producto_id')
    op.drop_column('pedido_items', 'pedido_id')
    op.drop_index(op.f('ix_cupones_codigo'), table_name='cupones')
    op.drop_column('cupones', 'max_usos_global')
    op.drop_column('cupones', 'max_usos_por_usuario')
    op.drop_column('cupones', 'fecha_expiracion')
    op.drop_column('cupones', 'activo')
    op.drop_column('cupones', 'descuento')
    op.drop_column('cupones', 'codigo')
    op.drop_constraint(None, 'cupon_usos', type_='foreignkey')
    op.drop_constraint(None, 'cupon_usos', type_='foreignkey')
    op.drop_column('cupon_usos', 'fecha_uso')
    op.drop_column('cupon_usos', 'cupon_id')
    op.drop_column('cupon_usos', 'usuario_id')
    # ### end Alembic commands ###
