"""Integracion de tablas de promociones

Revision ID: ecb4aaa788ae
Revises: ca517e614aaa
Create Date: 2025-07-13 20:10:27.226825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb4aaa788ae'
down_revision: Union[str, Sequence[str], None] = 'ca517e614aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocion_categoria',
    sa.Column('promocion_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promociones.id'], )
    )
    op.add_column('promocion_producto', sa.Column('promocion_id', sa.Integer(), nullable=True))
    op.add_column('promocion_producto', sa.Column('producto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'promocion_producto', 'promociones', ['promocion_id'], ['id'])
    op.create_foreign_key(None, 'promocion_producto', 'productos', ['producto_id'], ['id'])
    op.add_column('promociones', sa.Column('descuento_procentaje', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promociones', 'descuento_procentaje')
    op.drop_constraint(None, 'promocion_producto', type_='foreignkey')
    op.drop_constraint(None, 'promocion_producto', type_='foreignkey')
    op.drop_column('promocion_producto', 'producto_id')
    op.drop_column('promocion_producto', 'promocion_id')
    op.drop_table('promocion_categoria')
    # ### end Alembic commands ###
